fix(various): random album pagination fix - #749
navidrome/navidrome pull request #1023
Opened 2021-04-12 16:43 UTC by AeronCyther

# Closes
#749 

# Description
Added a way to seed the random sort used to order albums. 

# Changes
Added a middleware to handle random seeds in the form of cookies and add them to request's context when sorting albums by random. Added a context key to request. Implemented a pseudo-random function. Added a workaround for cases where random order mapping could not contain a comma (Example: "substr(id, 7)" turns into "order by substr(id asc, 7) asc" instead of "order by substr(id, 7) asc") by using a placeholder. 

# Notes
Currently the user stores the seed for 5 minutes since there is no way to differentiate between the api requests when the user has requested an album shuffle, and when the user just goes back to the first page (both requests only contain start and end). To get around this, the middleware looks for a "_shuffle" query. If found, it will generate a new seed. Once this is implemented, we may get rid of the 5 min expiry on the random seed.

2021-04-16 01:32 UTC, deluan commented
>Added a workaround for cases where random order mapping could not contain a comma (Example: "substr(id, 7)" turns into "order by substr(id asc, 7) asc" instead of "order by substr(id, 7) asc") by using a placeholder.

Hey @AeronCyther, can you please describe a situation where this may happen? Which URL could cause this?

> Currently the user stores the seed for 5 minutes since there is no way to differentiate between the api requests when the user has requested an album shuffle, and when the user just goes back to the first page (both requests only contain start and end).

I don't think this is necessary: If the user goes back to the first page, it _is_ a new album shuffle

2021-04-16 05:37 UTC, AeronCyther commented
> Hey @AeronCyther, can you please describe a situation where this may happen? Which URL could cause this?

@deluan Say for example, that my "random" function is ordering the entries by truncating their ids a bit. Then the random function could be "substr(id, 7)". But when squirrel gets that string as a parameter for SortBy, for some reason, it thinks that the comma is separating two sort parameters. An easy way to reproduce is to plug my random function in the master branch and debug print query after its creation in persistence/sql_base_repository.go. 

> I don't think this is necessary: If the user goes back to the first page, it _is_ a new album shuffle

Say I sort by random and I like an album on the first page, but I decide to go to next page to _just in case_ there's something better. I don't find anything I like so I go back to the first page using pagination (or even back button, but I don't see an easy solution for this), I wouldn't expect it to get randomised again.

2021-04-16 15:37 UTC, deluan commented
> But when squirrel gets that string as a parameter for SortBy, for some reason, it thinks that the comma is separating two sort parameters.

I'll take a look at that, but maybe this is on our side? https://github.com/navidrome/navidrome/blob/6ee45a9ccc5e7ea4290c89030e67c99c0514bd25/persistence/sql_base_repository.go#L64-L96

2021-04-16 15:58 UTC, AeronCyther commented
Seems like it is. I missed that. Either way, instead of trying to mess with that, since other code might depend on it, I decided to add a fallback instead.

2021-05-28 21:42 UTC, deluan commented
Hey @AeronCyther, I just pushed a fix to the issue with functions in the sort order. Let me know if you want to finish this.

2021-05-28 22:01 UTC, deluan requested changes

2021-05-28 22:01 UTC, deluan commented on persistence/sql_base_repository.go
> +	if _, ok := r.sortMappings["random-true"]; ok {
This should not be here, it is only related to albums, so should be in `album_repository`

2021-05-28 22:01 UTC, deluan commented on server/server.go
> +	r.Use(randomSeedMiddleware)
See comment in `middlewares.go`

2021-05-29 19:00 UTC, AeronCyther commented
@deluan I'll get to it ASAP

2023-09-07 01:44 UTC, closed without merging