Show what other users are playing on the server
navidrome/navidrome pull request #1027
Opened 2021-04-13 09:24 UTC by Rishabh-malhotraa

closes #769

shows what other users are playing in the activity menu.

> Hummm.... I took a look in the server code, and it seems that you bumped into a bug. This endpoint was created in 2016 and I never looked into it again after a lot of refactorings, and it seems to not be working properly.... To complete your code, try to mock the response with more info.
>
> In terms of design, maybe add a header, "Now playing", then you don't need to add "current playing" on every line. I think it is important to show Song and Artist and the time (minutesAgo). The Album name is not necessary. We should also truncate long names with ellipsis (...).

Based on feedback, requested changed

|doalog box| dialog Box II|
|-|-|
| ![Screenshot from 2021-04-13 14-13-39](https://user-images.githubusercontent.com/54576074/114529875-0a673580-9c68-11eb-81d7-ba120fe57493.png) | ![Screenshot from 2021-04-13 14-14-01](https://user-images.githubusercontent.com/54576074/114529930-17842480-9c68-11eb-8739-b88210ac9537.png) |

2021-04-13 09:25 UTC, Rishabh-malhotraa commented on ui/src/layout/ActivityPanel.js
> +  }, [dispatch, open])
the useEffect runs whenever open changes it state where open = Boolean(anchorEl) i.e whenever we either open/close the modal but we don't want to make an API call when we close the modal hence this check condtion.

2021-04-13 09:27 UTC, Rishabh-malhotraa commented on ui/src/layout/ActivityPanel.js
> +      '& .MuiListItemText-primary': {
this means for add following CSS to `.MuiListItemText-primary` wrapped around div with `class = "primary"`

2021-04-13 09:30 UTC, Rishabh-malhotraa commented on ui/src/layout/ActivityPanel.js
> +                      secondary="place-holder"
we need to add a "placeholder" to not break material UI CSS, i.e if we don't add a placeholder than css breaks for material UI like the following. we add visibility hidden to the div which contains the "place-holder" text 

![Screenshot from 2021-04-13 15-00-27](https://user-images.githubusercontent.com/54576074/114530904-02f45c00-9c69-11eb-8ffa-06be6a94e644.png)

2021-04-13 09:32 UTC, Rishabh-malhotraa commented on ui/src/layout/ActivityPanel.js
> +                      secondary="place-holder"
we need to add a "placeholder" to not break material UI CSS, i.e if we don't add a placeholder than css breaks for material UI like the following.
![Screenshot from 2021-04-13 15-00-27](https://user-images.githubusercontent.com/54576074/114530904-02f45c00-9c69-11eb-8ffa-06be6a94e644.png)

 we then hide the placeholder text by adding visibility hidden to it. 

``` js
    '& .MuiListItemSecondaryAction-root': {
      '& .MuiListItemText-secondary': {
        visibility: 'hidden',
      },
    },

```

2021-04-14 14:05 UTC, metalheim commented
Looks great IMHO :)

2021-05-04 02:12 UTC, deluan commented
Sorry for not give the proper attention to this PR, but I have to fix the `nowPlaying` endpoint before enabling this in the UI. Have to find the time... :/

2021-06-20 15:59 UTC, deluan commented
The `nowPlaying` endpoint is now fixed in master, I'll try to review and merge this for next release

2021-06-21 20:20 UTC, Rishabh-malhotraa commented
> The `nowPlaying` endpoint is now fixed in master, I'll try to review and merge this for next release

great looking forward to it 🙌

2021-06-25 17:45 UTC, deluan requested changes

2021-06-25 17:45 UTC, deluan commented on ui/src/layout/ActivityPanel.js
> +        .fetchJson(subsonic.url('getNowPlaying'))
Please create a new function in `subsonic/index.js` for this.

2021-06-25 17:45 UTC, deluan commented on ui/src/layout/ActivityPanel.js
> +                    secondary={`${user.title} - ${user.artist}`}
Can we add a link to the album here?

2021-06-25 17:53 UTC, deluan commented
Hey @Rishabh-malhotraa, I just tried it in my local and looks great, with only a couple of issues (see the review comments).
Also, can we make the `title - artist` lines wrap around to up to two lines? The width of the popup is not enough for most songs:

<img width="307" alt="Screen Shot 2021-06-25 at 1 29 36 PM" src="https://user-images.githubusercontent.com/331353/123465336-0044aa00-d5bc-11eb-8024-b706413068c3.png">

You'll need to pull the latest master...

2021-06-30 00:35 UTC, Rishabh-malhotraa commented
> Hey @Rishabh-malhotraa, I just tried it in my local and looks great, with only a couple of issues (see the review comments).
> Also, can we make the `title - artist` lines wrap around to up to two lines? The width of the popup is not enough for most songs:
> 
> <img alt="Screen Shot 2021-06-25 at 1 29 36 PM" width="307" src="https://user-images.githubusercontent.com/331353/123465336-0044aa00-d5bc-11eb-8024-b706413068c3.png">
> 
> You'll need to pull the latest master...

Thank you for the detailed review @deluan, I uninstalled ubuntu from my laptop on which I built navidrome, besides that I am quite busy preparing for coding interviews, regardless I'll try to build navidrome on window and get this done whenever I get some spare time.

2021-06-30 02:01 UTC, deluan commented
No rush. By the way, it may be easier to use WSL insteado of trying to setup de dev environment directly on Windows..

2021-06-30 09:56 UTC, Rishabh-malhotraa commented
> Also, can we make the `title - artist` lines wrap around to up to two lines? The width of the popup is not enough for most songs:

Rather than having wrap it around upto two lines what do you think about moving text from text to right, I checked on youtube music and they implement moving text on long albums names too

![ZdA7N.gif](https://user-images.githubusercontent.com/54576074/123940956-51d3a700-d9b7-11eb-8ae3-e1c569d11ad7.gif)

2021-06-30 13:41 UTC, deluan commented
@Rishabh-malhotraa, yeah that looks good!

2023-09-07 01:44 UTC, closed without merging