Enable transcoding of downlods
navidrome/navidrome pull request #1667
Opened 2022-03-26 02:22 UTC by kgarner7

Closes: #573

Enables transcoding downloaded songs, albums, playlist, and artists. 

To support transcoding downloads, I added two new parameters to the download API
- format: the target format to transcode to (the name, like mp3, opus)
- bitrate: the rate to transcode all songs. A value of 0 (or not provided) means to use the original bitrate

Optionally, with `AutoTranscodeDownlaod` set to true, downloads can be automatically transcoded using the transcoding configuration in the UI.

On the frontend, downloads now have a modal asking for a download choice: either use the original format, or transcode to a different format and optionally choose a bitrate. From the Navidrome UI, all download requests would provide the optional parameters above.

I tried my best to add minimal new text, but unfortunately I had to add some text to describe "original format". This is in `en.json`, `message.originalFormat`

2022-03-26 23:08 UTC, deluan commented
This looks awesome! I'll test it this week and give feedback, thanks!!

2022-06-09 13:02 UTC, vs49688 commented
I just gave this a try, a few things:

* The UI is broken:

   ![Screenshot_20220609_224805](https://user-images.githubusercontent.com/4423262/172851125-5ee75333-c92a-4b0e-a4fc-950fc5c8539f.png)

* Once I click download and select a format, I can't select a different format next time I try.

2022-06-09 18:49 UTC, kgarner7 commented
Thanks for testing! It looked fine on my end, but that's probably because of some other changes I had that fixed it .-.
I've fixed the display, but I'm not able to recreate the formatting issue?

2022-11-22 17:51 UTC, vsTerminus commented on conf/configuration.go
> +	AutoTranscodeDownlaod   bool
"Download" is spelled incorrectly here
```suggestion
	AutoTranscodeDownload   bool
```

2022-11-22 17:52 UTC, vsTerminus commented on server/subsonic/stream.go
> +		if conf.Server.AutoTranscodeDownlaod {
"Download" also spelled wrong here.
```suggestion
		if conf.Server.AutoTranscodeDownload {
```

2022-12-06 04:45 UTC, rsammelson commented on ui/src/App.js
> +  downloadMeuDialogReducer,
Menu is misspelled in this variable name.

2022-12-06 23:59 UTC, deluan requested changes
Hey, overall it is a great PR! Please take a look at my comments below. Thanks!

2022-12-06 23:59 UTC, deluan commented on core/media_streamer.go
> +	r, error := ms.cache.Get(ctx, job)
Please don't use `error` as a variable name as it colides with the builtin `error` interface.

2022-12-06 23:59 UTC, deluan commented on core/media_streamer.go
> +	_, err := io.Copy(w, r)
I think we need to close the reader returned by the `ms.Cache.Get()` method, like we do when calling `NewStreamer()`. By the way, why not use `NewStreamer` to obtain a `Reader` inside the `Archiver` and do the copy there? Why the need to introduce this `TranscodeDownload` method?

2022-12-06 23:59 UTC, deluan commented on server/subsonic/stream.go
> +			// This will implact other clients which do not use the UI
Typo:
```suggestion
			// This will impact other clients which do not use the UI
```

2022-12-06 23:59 UTC, deluan commented on server/subsonic/stream.go
> +		}
This is basically duplicated from the `Stream()` method above. Can we extract this into its own method?

2022-12-06 23:59 UTC, deluan commented on conf/configuration.go
> +	AutoTranscodeDownload   bool
I think this should be called `DefaultDownloadTranscoding` (or similar), as it can be overridden in the UI.

2022-12-06 23:59 UTC, deluan commented on ui/src/reducers/dialogReducer.js
> +export const DOWNLOAD_MENU_SONG = 'song'
I think these constants should be in the `actions/dialogs.js` file, as they are used only (AFAICT) as parameter to `openDownloadMenu` action

2022-12-18 04:25 UTC, deluan requested changes
LGTM, just a small error from my side and we we are good to merge!

2022-12-18 04:25 UTC, deluan commented on server/subsonic/stream.go
> +			// if we are not provided a format, see if we have requested transcoding for this client
Sorry, but I didn't get the purpose of this config when I first reviewer your PR. I think the previous name (`AutoTranscodeDownload `) actually makes more sense.

2022-12-18 17:12 UTC, merged