Fix Misleading Error Message on unreadable Media due to Permission
navidrome/navidrome pull request #1873
Opened 2022-09-17 10:49 UTC by reopt999

This PR is to fix misleading error message when Navidrome tries to extract the metadata from a media file that is unreadable due to Navidrome process has no permission to read the media file. Additionally, this PR is to fix Navidrome from storing dummy entry from media that are unreadable. Error message may be changed and some checks are probably needed to make it more consistent.

Tested on Archlinux.

Closes #1576

2022-09-30 14:12 UTC, reopt999 commented
Hi, @deluan there is a failed check, I'm not sure what is wrong. I noticed that other PR got annotations on which code caused the failure but I don't see any for this commit. Is there anything I can do?

2022-09-30 15:10 UTC, deluan requested changes
Thanks for this. The failed check is not your fault, it is caused by new formatting rules in Go 1.18. Just rebase your PR and it should work.

Can you please try to come up with a test for this? Maybe create a test file (copying from `tests/fixtures/test.mp3` and changing its permissions in the test setup?

2022-10-02 07:28 UTC, reopt999 commented on scanner/metadata/taglib/taglib.go
> +			fileTags[path] = tags
Thank you for the review, I have pushed a change to classify the error and only the unreadable file should be skipped

2022-12-04 00:50 UTC, deluan commented
Hey, I fix the tests (the assertions were not quite right) and did some clean-up as well. I still have to test this on Windows before merging, but in the meantime let me know if you have any concerns with my changes

2022-12-04 01:32 UTC, deluan approved these changes
LGTM. Still pending testing on Windows, hopefully will have it tested this weekend. Thanks!

2022-12-04 17:48 UTC, merged