feat(playlists): POST endpoint for importing m3u playlists - #2078
navidrome/navidrome pull request #2273
Opened 2023-03-22 17:08 UTC by SwatsonCodes

Closes [2078](https://github.com/navidrome/navidrome/issues/2078)

Description:
adds an HTTP post endpoint at `api/playlist` for uploading m3u playlists

Changes:
* Route POST requests to `api/playlist` based on content-type. Requests with `audio-xmpegurl` content type are parsed as a m3u playlist and imported.
* Minor refactor to core playlist parsing logic and interface to support parsing m3u playlists from an `io.Reader`. Previous code assumed a local file.
* Minor fix (workaround?) for locally failing test. I don't have much context here so my workaround may not be optimal, but it was blocking me. 

Example POST request:
```
curl -X POST \
-H "Content-Type: audio/x-mpegurl" \
-H "X-ND-Authorization: Bearer redacted" \
--data "`cat myplaylist.m3u`" \
localhost:4533/api/playlist
```

2023-03-26 23:58 UTC, deluan commented
Thanks @SwatsonCodes! I'll review as soon as I can (the backlog of PRs to review is huge ATM)

2023-04-12 00:48 UTC, deluan requested changes
Thanks for this. See my comments below. Also, we could add some tests here, specially to the `ImportM3U` method

2023-04-12 00:48 UTC, deluan commented on core/playlists.go
> +		if strings.HasPrefix(line, "#PLAYLIST:") {
We need to generate a playlist name, in case the posted M3U does not have a `#PLAYLIST:` directive. maybe a time stamp?

2023-04-12 00:48 UTC, deluan commented on core/playlists.go
> +			log.Warn(ctx, "Path in playlist not found", "playlist", pls.Name, "line", line, err)
The 5th param in this log line should be `"path"`

2023-04-12 00:48 UTC, deluan commented on core/playlists.go
> +	return s.parseM3U(ctx, pls, "", reader)
Similar to `ImportFile`, this method should save it to the DB.

2023-04-12 00:48 UTC, deluan commented on server/nativeapi/playlists.go
> +		err = ds.Playlist(ctx).Put(pls)
This should happen inside the `ImportM3U` method, as I commented above.

2023-04-12 00:48 UTC, deluan commented on server/nativeapi/playlists.go
> +		p := core.NewPlaylists(ds)
We already have the `core.Playlists` instantiated in the Router, we could pass it as a parameter, similar to what we are doing with the `model.DataStore`.

2023-08-16 15:50 UTC, caiocotts commented
Hey @spwats, are you planning in addressing these changes? If not, would it be ok if I work on them?

2023-08-16 15:53 UTC, spwats commented
Hi @caiocotts! Yes please, I'd be happy for you to pick up this PR. I feel bad for abandoning it, but I got a new job and no longer have time to work on open source stuff.

2023-08-16 16:02 UTC, caiocotts commented
It's all good man. Thanks for the fast response!

2023-10-29 21:31 UTC, caiocotts commented
Hey @deluan, I made the changes you requested, but I still have to write the tests. Let me know if there's anything else I'm missing.

2023-10-30 02:53 UTC, deluan commented
Looks good, thanks! Let me know if you need help with the tests.

2023-11-01 14:26 UTC, deluan commented on core/playlists_test.go
> +			f, _ = os.Open("tests/fixtures/playlists/pls-post-with-name.m3u")
There are two tests here. They should be in different `It`s

2023-11-01 18:59 UTC, deluan commented
Thanks @spwats and @caiocotts!

2023-11-01 18:59 UTC, merged

2023-11-01 20:21 UTC, spwats commented
Very happy to see this get completed! Thanks for picking up where I left off @caiocotts.

2023-11-02 14:12 UTC, samcro1967 commented
I tried this out this morning using the develop docker image.  I get the following response when I try to do an import:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    39  100    18    647    298 --:--:-- --:--:-- --:--:--   950
#EXTM3U
#PLAYLIST:2023-11-02T14:02:11Z
```

A playlist is created with a generic name based on timestamp and the test song is not added.  I do not see a way to set the playlist name.  Thinking it should come from the playlist filename???  Here is my script I am testing:
```
#!/bin/sh

# User credentials and server URL
USERNAME="<redacted>"
PASSWORD="<redacted>"
NAVIDROME_URL="<redacted>"

# Get Bearer token
TOKEN_RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\"}" "$NAVIDROME_URL/navidrome/auth/login")
BEARER_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r .token)

# Check if token was successfully retrieved
if [ "$BEARER_TOKEN" = "null" ] || [ -z "$BEARER_TOKEN" ]; then
  echo "Failed to retrieve Bearer token"
  exit 1
fi

# echo "Bearer Token: $BEARER_TOKEN"

# Playlist information
PLAYLIST_FILE="playlist.m3u"

# Import playlist
RESPONSE=$(curl -X POST \
  -H "Content-Type: audio/x-mpegurl" \
  -H "X-ND-Authorization: Bearer $BEARER_TOKEN" \
  --data "'cat $PLAYLIST_FILE'" \
  "$NAVIDROME_URL/navidrome/api/playlist")

echo "$RESPONSE"
```

Here is what the playlist I am testing with looks like.  I have copied the line from another playlist that was exported so I know the path is correct.
```
/music/Unmanaged/Singles/Dustin Lynch - Chevrolet (feat. Jelly Roll).mp3
```

The token is properly obtained.  I am able to export playlists so I think I have all of the URL's correct.  Guessing I am missing something, but not quite sure what.

2023-11-02 15:05 UTC, caiocotts commented
Hey @samcro1967.
The playlist name is set from the `#PLAYLIST` directive inside the M3U file. If it's not present, then a timestamp is used.

As for the song not getting added. Is the path `/music/` the volume you mounted on your navidrome instance, or is that path from your host machine? 

As a reference, this is the M3U I was using to test the endpoint, my navidrome was running directly on my machine without docker:
```
#EXTM3U
#PLAYLIST:Neat Sounds
#EXTINF:243,Kraftwerk - Morgenspaziergang
/home/caio/Music/Kraftwerk/Autobahn/01-05 Morgenspazisergang.mp3
#EXTINF:269,TOBACCO - Enough to Calm You Down
/home/caio/Music/TOBACCO/The Allegheny White Fish Tapes/01-06 Enough to Calm You Down.flac
#EXTINF:96,TOBACCO - Metal Ball Moon
/home/caio/Music/TOBACCO/The Allegheny White Fish Tapes/01-07 Metal Ball Moon.flac
#EXTINF:161,TOBACCO - The Love Song
/home/caio/Music/TOBACCO/The Allegheny White Fish Tapes/01-12 The Love Song.flac
#EXTINF:253,Morcheeba - Bullet Proof
/home/caio/Music/Morcheeba/Big Calm/01-06 Bullet Proof.flac
```

2023-11-02 15:17 UTC, samcro1967 commented
Yes, /music/ is what is mounted to the docker container.  I have validated that the path is correct.
```
~/Documents/Docker/navidrome$ docker exec -it navidrome /bin/sh
/app $ ls -al '/music/Unmanaged/Singles/Dustin Lynch - Chevrolet (feat. Jelly Roll).mp3'
-rwxrwx---    1 1000     users      6265272 Oct 31 16:49 /music/Unmanaged/Singles/Dustin Lynch - Chevrolet (feat. Jelly Roll).mp3
/app $
```

I get the same results with the following playlist.m3u:
```
#EXTM3U
#PLAYLIST:TEST
#EXTINF:184,Dustin Lynch - Chevrolet (Feat. Jelly Roll)
/music/Unmanaged/Singles/Dustin Lynch - Chevrolet (feat. Jelly Roll).mp3
```

2023-11-03 17:00 UTC, samcro1967 commented
I was able to get the import to work with the updated script below.

```
#!/bin/sh

# User credentials and server URL
USERNAME="<redacted>"
PASSWORD="<redacted>"
NAVIDROME_URL="<redacted>"
BASEURL=navidrome

# Get Bearer token
TOKEN_RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"username\":\"$USERNAME\",\"password\":\"$PASSWORD\"}" "$NAVIDROME_URL/$BASEURL/auth/login")
BEARER_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r .token)

# Check if token was successfully retrieved
if [ "$BEARER_TOKEN" = "null" ] || [ -z "$BEARER_TOKEN" ]; then
  echo "Failed to retrieve Bearer token"
  exit 1
fi

# echo "Bearer Token: $BEARER_TOKEN"

# Playlist information
PLAYLIST_FILE="playlist.m3u"

echo "---------------------------------------------------------------------------------------"
echo "PlaylistFile:  $PLAYLIST_FILE"
echo "-----------------------------"
cat $PLAYLIST_FILE
echo "\n---------------------------------------------------------------------------------------\n"

# Import playlist
RESPONSE=$(curl -X POST \
  -H "Content-Type: audio/x-mpegurl" \
  -H "X-ND-Authorization: Bearer $BEARER_TOKEN" \
  --data-binary @$PLAYLIST_FILE \
  "$NAVIDROME_URL/$BASEURL/api/playlist")

echo "\n---------------------------------------------------------------------------------------"
echo "Response:"
echo "$RESPONSE"
echo "---------------------------------------------------------------------------------------"
```