Fixed issue no #2174
navidrome/navidrome pull request #2299
Opened 2023-04-07 14:35 UTC by subhajit20

Fixed issue no #2174

2023-04-07 15:07 UTC, subhajit20 commented
@deluan  are you going to merge this with the master branch?

2023-04-08 01:31 UTC, deluan requested changes

2023-04-08 01:31 UTC, deluan commented on ui/src/App.js
> +      ]}{' '}
Can you please remove this space? Probably it was added by some reformatting by your code editor.

2023-04-08 14:30 UTC, subhajit20 commented
@deluan Hey I have pushed another commit.
Kindly check that once

2023-04-08 17:39 UTC, merged