[enhancement]: Support fetching lyrics from external sources
navidrome/navidrome pull request #2897
Opened 2024-03-10 01:34 UTC by kgarner7

- Adds LyricsRetriever interface to fetch lyircs from external source
- Adds external lyrics/updated at MediaFile (default caching of 1 month)
- Adds lrclib agent, which fetches from lrclib.net
- Updates local agent to read lyrics from track.txt/track.lrc

2024-08-09 17:49 UTC, TacoCake commented
What's missing for this PR to be merged?

2024-08-10 15:56 UTC, deluan commented
Currently I'm avoiding merging big PRs and introduce new functionalities as it creates conflicts with the Big Refactoring I'm working on #2709. Once that refactoring is done, I'll work with @kgarner7 to get his contributions merged.

2024-08-10 16:22 UTC, TacoCake commented
Ah, I see. Thanks for the clarification!

2025-02-25 16:55 UTC, olgam4 commented
Sorry for asking; was wondering if this would eventually be merged?

2025-02-25 16:56 UTC, deluan commented
Yes it will, after the next release I'll review it and workwith @kgarner7 to merge it.

2025-04-28 03:59 UTC, yodaluca23 commented
Just wondering if the API URL will be customizable in the Navidrome config, as LRC lib is OSS https://github.com/tranxuanthang/lrclib and people may want to self-host, or use other instances.

2025-04-28 12:47 UTC, deluan commented
Hey @yodaluca23, that's a good suggestion, thanks. 

Just keep in mind we decided to break this PR into two parts: local .lrc (this one) and a followup that will add lrclib support as a plugin. This one should merge soon, but the lrclib is blacked by #3998 , probably will take a 2-4 weeks to be available.

2025-04-28 12:47 UTC, deluan commented
@ellipsis-dev review this PR

2025-04-28 19:06 UTC, deluan commented on core/lyrics/lyrics.go
> +	for pattern := range strings.SplitSeq(strings.ToLower(conf.Server.LyricsPriority), ",") {
strings.SplitSeq returns a iter.Seq. It does not return a slice, so the code is correct

2025-04-28 19:06 UTC, deluan commented on tests/fixtures/test.lrc
> +[00:22.801]You know the rules and so do I
That's intentional

2025-04-28 19:32 UTC, deluan reviewed
LGTM. Will check it out in my local later to do some testing

2025-04-28 19:32 UTC, deluan commented on conf/configuration.go
> +	viper.SetDefault("lyricspriority", "embedded,.lrc,.txt")
I think the default should be `.lrc,.txt,embedded`, to maintain consistency with coverart (`cover.*, folder.*, front.*, embedded, external`)

2025-04-28 19:32 UTC, deluan commented on consts/consts.go
> +	LyricsInfoTimeToLive      = 24 * time.Hour
We are not using this in this PR

2025-04-28 19:32 UTC, deluan commented on core/lyrics/lyrics.go
> +func GetLyrics(ctx context.Context, mf *model.MediaFile) (model.LyricList, error) {
I was thinking that this would be a struct, with a constructor that would allow us to inject the external.Provider (similar to artwork/artwork.go). But that's fine, I can refactor that as part of introducing the LyricsRetriever interface in the provider.

2025-04-28 19:36 UTC, deluan commented on core/lyrics/lyrics.go
> +		} else if len(lyricsList) > 0 {
No need for an `else` following a return. Less nesting

2025-04-28 19:40 UTC, deluan commented on core/lyrics/sources.go
> +	ext := filepath.Ext(basePath)
I think this should be path.Ext(), as paths are stored in the DB with `/`, never with local `PathSeparator`, IIRC.

2025-04-28 19:42 UTC, deluan commented
We should add (trace/debug) logging, to help troubleshooting lyrics resolution.

2025-04-29 00:38 UTC, kgarner7 commented on core/lyrics/lyrics.go
> +func GetLyrics(ctx context.Context, mf *model.MediaFile) (model.LyricList, error) {
The way I saw it was, external lyrics would just provide a string (and maybe a language) and let Navidrome parse it.

2025-04-29 00:46 UTC, deluan commented on core/lyrics/lyrics.go
> +func GetLyrics(ctx context.Context, mf *model.MediaFile) (model.LyricList, error) {
I see it as a core service, the source of truth for lyrics. So it will have to query external providers, similar to how artwork.Artwork does it. And to be able to do it, we need to inject the external.Provider into it and it needs to hold the reference. The pattern in the codebase is to use a struct for that.

2025-04-29 21:58 UTC, deluan reviewed
Check my comments. Not sure if we ever gonna return error from these `from*` functions.

2025-04-29 21:58 UTC, deluan commented on core/lyrics/sources.go
>  		return nil, err
In this case (ex: lack of permissions), should we return the error, or just log it as log.Error and return nil, nil? As it is right now, if the user configure priority as `.lrc,embedded`, and there is a permission error, if does not try the embedded version.

2025-04-29 21:58 UTC, deluan commented on core/lyrics/sources.go
>  		return nil, err
Same here. If the file is invalid, we don't want Navidrome to not try the embedded one, right?

2025-04-30 01:27 UTC, kgarner7 commented
> Check my comments. Not sure if we ever gonna return error from these `from*` functions.

`fromEmbedded` can return an error if someone modified the lyrics JSON to make it no longer valid.
`fromExternalFile` would thrown an error if permissions, but I'll modify `lyrics.go` to allow for errors (and add a test for it)

2025-04-30 01:54 UTC, kgarner7 commented on core/lyrics/sources.go
>  		return nil, err
If permission error, I would consider this a real error. This will be logged in `lyrics.go` and then fallthrough instead.

2025-04-30 01:55 UTC, kgarner7 commented on core/lyrics/sources.go
>  		return nil, err
Error will be logged, but fallthrough instead.

2025-04-30 02:01 UTC, deluan requested changes
Last one, I promisse :)

2025-04-30 02:01 UTC, deluan commented on server/subsonic/media_retrieval.go
> +	mediaFiles, err := api.ds.MediaFile(r.Context()).GetAll()
Any particular reason why you removed the filter?

2025-04-30 02:01 UTC, deluan commented on server/subsonic/media_retrieval.go
> +	} else if len(structuredLyrics) == 0 {
Nit: no need for an `else` following a return

2025-04-30 02:03 UTC, kgarner7 commented on server/subsonic/media_retrieval.go
> +	mediaFiles, err := api.ds.MediaFile(r.Context()).GetAll()
Yes, the filter only works when there are embedded lyrics and would preclude searching for lyrics by file (or, plugin) when that comes.

2025-04-30 02:08 UTC, kgarner7 commented on server/subsonic/media_retrieval.go
> +	mediaFiles, err := api.ds.MediaFile(r.Context()).GetAll()
Ah, I do see the need for artist/title filter. Let me add that test.

2025-04-30 12:10 UTC, merged

2025-05-09 17:28 UTC, frjol commented
Nice. I was looking just for that. I wonder when will the docker image be in sync with that?

2025-05-10 04:24 UTC, kgarner7 commented
If you want `deluan/navidrome:latest` (stable), you'll need to wait for the release. Otherwise, you could use [develop](https://hub.docker.com/layers/deluan/navidrome/develop/images/sha256-bf0fd8827551f0087b1a8a3b7215d17898b7316f44de212162b333b6f1b29ca2), with the caveat that this is unstable.