Added breakpoints for user input for the player
navidrome/navidrome pull request #848
Opened 2021-03-15 18:36 UTC by the-pro

Resolves #520 

Added the input for the user to give the appropriate breakpoints for the player and the player now works on those inputs

2021-03-16 11:09 UTC, jvoisin commented
Can you please add screenshots, so everyone can see what your changes are doing?

2021-03-16 12:01 UTC, the-pro commented
Yeah sure

I added a select list of breakpoints for users to select according to their screen size and choice :
![Screenshot from 2021-03-16 17-24-49](https://user-images.githubusercontent.com/42973786/111305422-f1755f80-867c-11eb-86ac-c1bf3db6db97.png)

If the break point is set >= their screen size then it will change the player :

![Screenshot from 2021-03-16 17-25-37](https://user-images.githubusercontent.com/42973786/111305670-3e593600-867d-11eb-8e77-c67cc3e527b0.png)

2021-03-17 04:04 UTC, deluan requested changes
Thanks for this, please take a look at the comments below. Also, I found two visual issues:
1. When first loading the UI with your changes, there's no default value, and the behaviour is unexpected:
<img width="378" alt="Screen Shot 2021-03-16 at 11 52 03 PM" src="https://user-images.githubusercontent.com/331353/111413133-12a57280-86b4-11eb-9787-7baf2f711190.png">

and the style of the input is wrong (does not match the other inputs:
<img width="422" alt="Screen Shot 2021-03-16 at 11 50 44 PM" src="https://user-images.githubusercontent.com/331353/111413235-3cf73000-86b4-11eb-80af-c5f959f23679.png">

2021-03-17 14:13 UTC, the-pro commented on ui/src/personal/Personal.js
> +      label={'select mobile player resolution'}
I have added the translate function and configured the language file accordingly but it does not work on any other translation than english

2021-03-21 17:56 UTC, deluan commented on ui/src/personal/Personal.js
> +      label={'select mobile player resolution'}
That's fine. This function does not translate automatically. When/If this PR is merged, we can receive contributions to the [translation files](https://github.com/navidrome/navidrome/tree/fbe6ecea95c153cc520386291e95df3f0b11b170/resources/i18n)

2021-03-21 17:59 UTC, deluan commented
I think the UX is still not great.... I'll have to spend some time trying to sort it out, and then will come back to this with some feedback. Thanks for your work on this so far.

PS: There may be some wrong usage of Redux somewhere in your code. I see this message in the browser's console if I start an incognito session:
<img width="643" alt="Screen Shot 2021-03-21 at 1 51 21 PM" src="https://user-images.githubusercontent.com/331353/111915643-aa58e700-8a4d-11eb-8845-c573873b095a.png">

2021-03-22 12:55 UTC, the-pro commented
I am thinking of storing it right in the local storage directly. Would that be alright

2021-03-23 07:54 UTC, the-pro commented
sir @deluan could you have a look at this commit. I have changed the use of redux store to localStorage.

2021-03-26 03:11 UTC, deluan commented
Sorry for the late reply. We have to avoid using localStorage as much as we can. Specially because in the future Preferences will go to the server and if it is all in Redux, we can just implement something like a Redux Saga to send the data to the server.

I know that handling Redux can be overwhelming at first, but I think this is a good opportunity for you to learn more about it, as it is one of the most used frameworks to handle state in React.

2022-11-27 16:34 UTC, deluan commented
Hey, I'm closing this as I'll need to rewrite the UI with the new React-Admin version (v4) and will try to implement this in a different way. Thanks anyway for the contribution!

2022-11-27 16:34 UTC, closed without merging