Bulk actions toolbar bug
navidrome/navidrome pull request #898
Opened 2021-03-24 05:19 UTC by RitikPandey1

#896 Bug Fixed :

![navidromeBugFixed](https://user-images.githubusercontent.com/57366926/112258646-d6ae7680-8c8c-11eb-9529-ff8779c3e5fb.gif)

`BulkDeleteButton` call `unselectAll` function which dispatch action to list reducer and unselect all selected ids from state, but list state of resource 'playlistTrack' have nothing in it because  `<List>`  or  `<ListBase>` components are not used.  I have fixed the bug by passing `onUnselectItems` function in `onClick`  prop of `BulkDeleteButton`.

Requesting review 
@deluan  @jvoisin

2021-03-24 14:03 UTC, deluan commented
Thanks for this! Will review and try it tonight!

2021-03-25 03:20 UTC, deluan requested changes
Thanks for the PR, but it is including commits from your previous PR. Can you please rebase it from master?

2021-03-25 05:23 UTC, RitikPandey1 commented
> Thanks for the PR, but it is including commits from your previous PR. Can you please rebase it from master?

Done 👍 
Thank you! for review @deluan

2021-03-26 01:39 UTC, deluan approved these changes
LGTM. Thanks!

2021-03-26 01:40 UTC, merged