Album details UI fix
navidrome/navidrome pull request #922
Opened 2021-03-28 19:43 UTC by rochakjain361

Fixes https://github.com/navidrome/navidrome/issues/910
Before:
![112582542-c3caac00-8e1c-11eb-94c5-a7aec7eebc11](https://user-images.githubusercontent.com/57208018/112765613-9142ce00-902b-11eb-88f7-3fe2473420d6.png)
Now: 
![Screenshot from 2021-03-29 01-11-15](https://user-images.githubusercontent.com/57208018/112765644-bd5e4f00-902b-11eb-8700-ea39951c935e.png)

2021-03-29 06:33 UTC, rochakjain361 commented
@deluan @jvoisin Can you review this code? And mention any changes if required.

2021-03-30 02:02 UTC, deluan requested changes
Thanks for PR. There is a big gap between the Album row and the first field in the details:
<img width="680" alt="Screen Shot 2021-03-29 at 10 00 20 PM" src="https://user-images.githubusercontent.com/331353/112922372-65caec80-90da-11eb-8cb4-5e8ffd038929.png">

This does not happen with the Song detail:
<img width="744" alt="Screen Shot 2021-03-29 at 10 00 32 PM" src="https://user-images.githubusercontent.com/331353/112922414-74b19f00-90da-11eb-8505-04890fac707e.png">

2021-03-30 02:02 UTC, deluan commented on ui/src/album/AlbumListView.js
> +  console.log(props)
Please remove

2021-03-30 22:53 UTC, rochakjain361 commented
@deluan I've made the requested changes to the pull request, can you please review it.

![Screenshot from 2021-03-31 03-24-48](https://user-images.githubusercontent.com/57208018/113065329-4e712980-91d6-11eb-8f09-8bcedc3674ad.png)

![Screenshot from 2021-03-31 03-25-04](https://user-images.githubusercontent.com/57208018/113065332-4fa25680-91d6-11eb-801d-b15922b30e56.png)

Also, I have a suggestion before closing this issue, we should display the artist's name in the album's detail view. While importing albums, the album's artist is taken as `Various Artists` many times and the real artist's name was in the `Artist` field. So it will be better if we display the Artist's name as well. 

![Screenshot from 2021-03-31 04-23-13](https://user-images.githubusercontent.com/57208018/113066826-d2c4ac00-91d8-11eb-8e6a-1ced6ffc6505.png)

2021-04-02 03:02 UTC, deluan commented
Thanks for the PR. LGTM, merging.

>While importing albums, the album's artist is taken as Various Artists many times and the real artist's name was in the Artist field

There is no "real artist" for a "various artists" album, only for the songs contained in it. Ex: "Best of 2017", various artists (it is a compilation): who is the "real artist"?

We will probably show all artists in that album when we get multiple artists (#238) in place.

2021-04-02 03:03 UTC, merged