Added Ratings feature with option to turn on/off the Ratings feature
navidrome/navidrome pull request #986
Opened 2021-04-05 16:06 UTC by neilchauhan2

## Update with this PR.
- Added Ratings feature to the UI.
- Added option to turn on/off Ratings feature.

## UI Preview with Ratings enabled.
![on-s-1](https://user-images.githubusercontent.com/31568159/113595286-7210f580-9656-11eb-82df-8b5fb620c510.png)
![on-s-2](https://user-images.githubusercontent.com/31568159/113595292-73dab900-9656-11eb-9302-ad0d600c88d7.png)
![on-al-1](https://user-images.githubusercontent.com/31568159/113595314-789f6d00-9656-11eb-822c-53a3c6d61480.png)
![on-al-2](https://user-images.githubusercontent.com/31568159/113595321-79d09a00-9656-11eb-999e-8965bda7580f.png)
![on-al-3](https://user-images.githubusercontent.com/31568159/113595330-7b9a5d80-9656-11eb-9af9-cc7fca234ed1.png)
![on-al-4](https://user-images.githubusercontent.com/31568159/113595335-7d642100-9656-11eb-85a7-1107b4b67655.png)
![on-a-1](https://user-images.githubusercontent.com/31568159/113595348-8228d500-9656-11eb-9a90-eebb9285840a.png)

## UI Preview with Ratings disabled.
![off-s-1](https://user-images.githubusercontent.com/31568159/113595480-b3090a00-9656-11eb-8798-f770f35df5c7.png)
![off-s-2](https://user-images.githubusercontent.com/31568159/113595481-b3a1a080-9656-11eb-88e3-0c88edac0d8c.png)
![off-a-1](https://user-images.githubusercontent.com/31568159/113595491-b7352780-9656-11eb-867d-22f2f25e56dc.png)
![off-a-2](https://user-images.githubusercontent.com/31568159/113595496-b8665480-9656-11eb-833d-e861853b5f5b.png)
![off-al-1](https://user-images.githubusercontent.com/31568159/113595501-bac8ae80-9656-11eb-8273-e449fe987246.png)
![off-al-2](https://user-images.githubusercontent.com/31568159/113595513-bdc39f00-9656-11eb-9547-0b7fa41bf200.png)
![off-al-3](https://user-images.githubusercontent.com/31568159/113595524-bef4cc00-9656-11eb-980b-5e47842901c9.png)
![off-al-4](https://user-images.githubusercontent.com/31568159/113595539-c1572600-9656-11eb-9659-03a293c2052c.png)

This PR fixes #639

2021-04-06 04:01 UTC, deluan commented
Thanks for this! I captured a few bugs with this PR:


https://user-images.githubusercontent.com/331353/113656990-084f1680-966b-11eb-9c64-7491fc1a5c36.mov


https://user-images.githubusercontent.com/331353/113656996-08e7ad00-966b-11eb-9390-1abd946be577.mov


<img width="1469" alt="Screen Shot 2021-04-05 at 11 53 59 PM" src="https://user-images.githubusercontent.com/331353/113656955-f4a3b000-966a-11eb-9011-45a2327c1f60.png">

Also, I could not find a way to reset/remove the stars from an item.

2021-04-06 12:40 UTC, neilchauhan2 commented
@deluan I have resolved the bugs, please review this PR once again. 

> Also, I could not find a way to reset/remove the stars from an item.

This works exactly the same way as in other platforms. You have to click the currently selected star to remove ratings or reset it to 0. For example, a particular song has 3 star ratings, so you will see 3 lighted stars, click on the 3rd lighted star and the ratings would be removed i.e. set back to 0.

2021-04-07 02:46 UTC, deluan requested changes
This looks good! Seems to be working fine. Besides the couple of small issues in the comments below, you should also add translations for the `rating` columns in the `en.json` file

2021-04-07 02:46 UTC, deluan commented on ui/src/common/RatingField.js
> +    visibility: (props) => (props.visible === false ? 'hidden' : 'inherit'),
Can you add `color: 'inherit'`, to make it "blend" better with the theme?

2021-04-07 02:46 UTC, deluan commented on ui/src/common/RatingField.js
> +  size: 'medium',
I think the default should be "small", to be less "aggressive" when used as a column in the DataGrids

2021-04-07 02:50 UTC, deluan commented
Can you also add a "Top Rated" Sub Menu in the Albums List? Take a look at the `ui/src/album/albumList.js` file. Add it after the "starred" option. It will also require a translation here: https://github.com/navidrome/navidrome/blob/ac37bf3631610747001f44fe843517f3fdf0ac08/ui/src/i18n/en.json#L63

2021-04-07 15:06 UTC, deluan commented on ui/src/album/albumLists.js
> +      params: 'sort=rating&order=DESC',
I just added a `has_rating` filter in the album_repository, you can set it with:
```
&filter={"has_rating":true)
```
So only rated albums will show up in this view

2021-04-07 15:08 UTC, deluan commented on ui/src/album/albumLists.js
> +    rating: {
This should be called `topRated`

2021-04-07 16:22 UTC, neilchauhan2 commented
@deluan I've made all the improvements mentioned by you in the above comments, as well as included the empty stars icon. Please review the PR.

2021-04-07 16:30 UTC, deluan commented
Hey @neilchauhan2 , looks really good, thanks! One small thing slipped through the cracks: In the `AlbumSongs.js`, the `RatingField` should have `sortable={false}`, or else it make the column sortable, something we don't want in this view

2021-04-07 16:33 UTC, deluan commented
You should also change the `sortByOrder` attribute to `DESC` in `SongList.js` (and probably in all other lists), so then when a user sorts the list by rating, the top rated appears first

2021-04-07 17:18 UTC, deluan requested changes

2021-04-07 17:18 UTC, deluan commented on ui/src/i18n/en.json
> +        "rating": "Rating",
I think you are still missing the `rating` field for albums and artists in this file.

2021-04-07 17:20 UTC, deluan requested changes

2021-04-07 17:20 UTC, deluan commented on ui/src/album/AlbumListView.js
> +                sortByOrder={'DESC'}
Here it is not necessary, it is only used for making the header clickable in the DataGrid, not in SimpleLists

2021-04-07 17:25 UTC, neilchauhan2 commented
@deluan I'll make these changes in some time, till then you can check if there is anything else that needs to be improved.

2021-04-07 17:37 UTC, deluan commented
Ok, will take a throughly testing and will let you know, thanks a lot for this!

2021-04-07 18:54 UTC, deluan commented
> @deluan I'll make these changes in some time, till then you can check if there is anything else that needs to be improved.

I think that's it. After removing `sortByOrder={'DESC'}` from SimpleLists, we are good to merge!

2021-04-07 20:02 UTC, deluan commented
I think that's it! Thanks for your effort! Merging it now

2021-04-07 20:02 UTC, merged